### ISSUE TITLE
ArSnap does not work, RpcProvider gets unknown response id

### ISSUE THREAD

**Issue by Sirgulator** [pianity/arsnap#14]
Tested on Chromium 103.0.5060.114 and Metamask Flask: 10.17.0-flask.0
Error direct on loading page.

```
inpage.js:1 MetaMask: Lost connection to "MetaMask RpcProvider".
Error: StreamMiddleware - Unknown response id "3128787891"
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:55198
    at d.write [as _write] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:55316)
    at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:17:29867)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:17:33045
    at y.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:17:33072)
    at i.g (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:17:22073)
    at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:8:21088)
    at o.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:8:24074)
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:17:16876)
    at v (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:17:16691)
_handleStreamDisconnect @ inpage.js:1
inpage.js:1 Error: StreamMiddleware - Unknown response id "3128787891"
    at l._handleDisconnect (inpage.js:1:38747)
    at l._handleDisconnect (inpage.js:1:42344)
    at l._handleStreamDisconnect (inpage.js:1:46473)
    at inpage.js:17:12354
    at t (inpage.js:17:8407)
    at d.<anonymous> (inpage.js:17:11676)
    at d.t (inpage.js:17:8407)
    at d.h (inpage.js:8:27815)
    at d (inpage.js:8:21053)
    at o.emit (inpage.js:8:24049)
_handleDisconnect @ inpage.js:1
inpage.js:1 MetaMask: Lost connection to "MetaMask RpcProvider".
Error: StreamMiddleware - Unknown response id "2088519189"
    at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/inpage.js:1:55198
    at d.write [as _write] (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/inpage.js:1:55316)
    at w (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/inpage.js:17:29867)
    at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/inpage.js:17:33045
    at y.write (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/inpage.js:17:33072)
    at i.g (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/inpage.js:17:22073)
    at f (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/inpage.js:8:21088)
    at o.emit (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/inpage.js:8:24074)
    at _ (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/inpage.js:17:16876)
    at v (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/inpage.js:17:16691)
_handleStreamDisconnect @ inpage.js:1
inpage.js:1 Error: StreamMiddleware - Unknown response id "2088519189"
    at l._handleDisconnect (inpage.js:1:38747)
    at l._handleDisconnect (inpage.js:1:42344)
    at l._handleStreamDisconnect (inpage.js:1:46473)
    at inpage.js:17:12354
    at t (inpage.js:17:8407)
    at d.<anonymous> (inpage.js:17:11676)
    at d.t (inpage.js:17:8407)
    at d.h (inpage.js:8:27815)
    at d (inpage.js:8:21053)
    at o.emit (inpage.js:8:24049)
```

**Comment by noomly** [comment]
Hey there, thanks for submitting an issue!

Can you give more detail about the version of Arsnap on which you're experiencing this issue? Did you build it from source or are you using the deployed Wallet at arsnap.org?

Also, can you check whether Arsnap is listed in the "Snaps" section of Metamask's settings?

**Comment by Sirgulator** [comment]
This was tested on arsnap.org, page was stuck on loading, full log was supplied.
Arsnap has not connected to metamask, not in the settings

**Comment by noomly** [comment]
Thanks for the additional info. This sounds like it's an issue with Metamask, I'll forward it to their Snap team.

Just to be sure I understand how the issue manifests, when you say

> Error direct on loading page

Do you mean that the page is stuck in the loading animation even before you press any of the two "Connect with Metamask" button? Do they even show up?

Also, did you grab the logs from the page's console or from Metamask's background script's console?

**Comment by noomly** [comment]
I got an answer from someone at Metamask and they suggested the error you see could come from having both Metamask and Metamask Flask installed on your browser. Is it the case for you?

If it is, then it's due to some implementation details on Metamask's end. The only workaround here is to temporarily disable Metamask while running Metamask Flask on your browser.
